name: Notify Homebrew Repo

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger formula update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.HOMEBREW_REPO_PAT }}
          repository: ingk/homebrew-chrono-ntp
          event-type: update-formula
