name: Build and Release

on:
  workflow_dispatch:

env:
  GO_VERSION: '1.24.2'

jobs:
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            runs_on: ubuntu-latest
          - goos: linux
            goarch: arm64
            runs_on: ubuntu-24.04-arm
          - goos: windows
            goarch: amd64
            runs_on: ubuntu-latest
          - goos: windows
            goarch: arm64
            runs_on: ubuntu-24.04-arm
          - goos: darwin
            goarch: amd64
            runs_on: ubuntu-latest
          - goos: darwin
            goarch: arm64
            runs_on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs_on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install development dependencies
        if: ${{ matrix.goos == 'linux' }}
        run: sudo apt install -y libasound2-dev

      - name: Build
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          if [ "${{ matrix.goos }}" = "linux" ]; then
            CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/chrono-ntp-${{ matrix.goos }}-${{ matrix.goarch }} ./src/...
          else
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/chrono-ntp-${{ matrix.goos }}-${{ matrix.goarch }}$EXT ./src/...
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrono-ntp-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/chrono-ntp-${{ matrix.goos }}-${{ matrix.goarch }}*

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v5
      with:
        path: dist

    - name: Copy LICENSE
      run: cp LICENSE.txt dist/

    - name: Create tag variable
      id: tag
      run: |
        TAG=v$(date +%Y%m%d%H%M)
        echo "$TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Create tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ steps.tag.outputs.tag }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/**/*
        fail_on_unmatched_files: true
        tag_name: ${{ steps.tag.outputs.tag }}
        name: chrono-ntp ${{ steps.tag.outputs.tag }}
